# TODO - This config is not working. Can't reach database

FROM golang:1.25-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o main ./cmd/api

ENV DATABASE_URL=jdbc:postgresql://db.jgblagfgerdwcnbevjdz.supabase.co:5432/postgres?user=postgres&password=qUaZYODeurLkFsIi
ENV PORT=8080

EXPOSE 8080

CMD ["./main"]

